### ISSUE TITLE
Cannot disable tb name

### ISSUE THREAD

**Issue by cbandy** [kulti/thelper#28]
I would like to disable the check that suggests `testing.TB` be named `tb` (related #27) but I cannot figure out how.

The docs link to [`.golangci.example.yml`](https://golangci-lint.run/usage/configuration/#config-file) which says that all checks are enabled by default. I tried setting `tb: { name: false }`, `tb: { name: true }`, and others without any change in behavior. Is it possible to disable a check through golangci-lint?

Files:
```go
// ==> go.mod <==
module tmp

go 1.17

// ==> main_test.go <==
package main

import "testing"

func helper(t testing.TB) { t.Helper() }

func TestHelper(t *testing.T) { helper(t) }
```
```yaml
# ==> .golangci.yaml <==
linters:
  disable-all: true
  enable: [thelper]

linters-settings:
  thelper:
    tb_name: false
    tb:
      name: false
```

```console
$ go test .
ok      tmp     0.002s

$ golangci-lint version
golangci-lint has version 1.43.0 built from 861262b7 on 2021-11-03T11:57:46Z

$ golangci-lint run
main_test.go:5:6: parameter testing.TB should have name tb (thelper)
func helper(t testing.TB) { t.Helper() }
     ^
```

**Comment by kulti** [comment]
Thank you for your report.

It happens because golangci-lint has another approach to configure this linter. If you don't want to use all checks, you should specify only required checks. E.g.:
```
linters-settings:
  thelper:
    test:
      name: true
      first: true
      begin: true
    benchmark:
      name: true
      first: true
      begin: true
```

**Comment by kulti** [comment]
No any fixes required.

@cbandy, hope you completed your linters configuration. Feel free to reopen issue or ask me any other help.

**Comment by powerman** [comment]
Actually this doesn't works:
```yaml
linters-settings:
  thelper:
    # The following configurations enable all checks.
    # All checks are enabled by default.
    test:
    #  first: true
      name: false
    #  begin: true
    #benchmark:
    #  first: true
    #  name: true
    #  begin: true
    #tb:
    #  first: true
    #  name: true
    #  begin: true
```
Tested on golangci-lint v1.46.0.

`thelper -checks=b_begin,b_first,b_name,t_begin,t_first,tb_begin,tb_first,tb_name` works, so it's golangci-lint issue.

**Comment by kulti** [comment]
@powerman, that is not an issue. You cannot configure golangci-lint using `false`. As I mention before you should enable required checks (not disable unneeded).

**Comment by powerman** [comment]
Look: https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml#L1447-L1453
First comment lies ("The following configurations enable all checks." but all set to `false`).
Second comment says "All checks are enabled by default." (and it actually works this way).
So, how can I disable just `t_name` check in golangci-lint?

**Comment by kulti** [comment]
@powerman, as I mention before you should enable required checks:
```yaml
linters-settings:
  thelper:
    test:
      # name: true
      first: true
      begin: true
    benchmark:
      name: true
      first: true
      begin: true
    tb:
      first: true
      name: true
      begin: true
```

@ldez, FYI. I think the current example missconfusing users (was changed in https://github.com/golangci/golangci-lint/pull/2501).
