### ISSUE TITLE
thelper doesn't work inside golangci-lint when the analysed project use go1.17

### ISSUE THREAD

**Issue by ldez** [kulti/thelper#37]
## Step to reproduce

- use go1.17 (**IMPORTANT**)
- use golangci-lint v1.46.0 or v1.46.1 (compiled with go1.18)
- use the following files:

<details>
<summary>`go.mod`</summary>

```
module github.com/example/sandbox

go 1.17
```

</details>

<details>
<summary>`foo_test.go`</summary>

```go
package sandbox

import "testing"

func thelperWithHelperAfterAssignment(t *testing.T) {
	_ = 0
	t.Helper()
}

func thelperWithNotFirst(s string, t *testing.T, i int) {
	t.Helper()
}

func thelperWithIncorrectName(o *testing.T) {
	o.Helper()
}
```

</details>

<details>
<summary>`.golangci.yml`</summary>

```yml
linters:
  disable-all: true
  enable:
    - typecheck
    - thelper

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0

```

</details>

## Got

No issue reported:

```console
$ golangci-lint run
$
```

## Want

```console
$ golangci-lint run
foo_test.go:5:6: test helper function should start from t.Helper() (thelper)
func thelperWithHelperAfterAssignment(t *testing.T) {
     ^
foo_test.go:10:6: parameter *testing.T should be the first or after context.Context (thelper)
func thelperWithNotFirst(s string, t *testing.T, i int) {
     ^
foo_test.go:14:6: parameter *testing.T should have name t (thelper)
func thelperWithIncorrectName(o *testing.T) {
     ^
```
